```{r}
# ---- Cleanup everything before start ----
options(warn=-1)
rm(list = ls())
gc()
```

```{r}
### Find true capital-state pairs from all possible capital-state pairs

# ---- GBSERVER API ----
source("./Rscript/experimentAPI.R")
# ---- INPUT and CONFIGURATIONS ----

EDGE_TYPE_FILE = "./data/infobox.edgetypes" # Example : "../data/lobbyist.edgetypes"
CLUSTER_SIZE = 1 # Number of workers in gbserver
FALSE_PER_TRUE = 5
DISCARD_REL = 191
ASSOCIATE_REL = c(404)
max_depth = 3

# ---- Load edge type file ----
mapfile <- read.csv(EDGE_TYPE_FILE, sep="\t", header=F)
mapfile$V1 <- as.numeric(mapfile$V1)
mapfile$V2 <- as.character(mapfile$V2)
```

```{r}
list.of.packages <- c("FSelector", "ggplot2")
new.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[,"Package"])]
if(length(new.packages)) install.packages(new.packages, repos="http://cran.rstudio.com/")
library(FSelector)
library(ggplot2)
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
# ---- Load input data ----
INPUT_FILE = "./data_id/state_capital.csv" # Example : "../facts/lobbyist/firm_payee.csv" col 1 and 2 are ids and 3 is label
dat_state_capital.true <- read.csv(INPUT_FILE)

if (ncol(dat_state_capital.true) < 3)
  dat_state_capital.true$label <- T

# ---- Construct false labeled data -----
set.seed(233)

# TODO: reformat this so it is universal and file independent
dat_state_capital.false <- rbind.fill(apply(dat_state_capital.true, 1, function(x){
  candidates <- unique(dat_state_capital.true[which(dat_state_capital.true[,1] != x[1]), 2])
  candidates <- unlist(lapply(candidates, function(y){
    if(length(which(dat_state_capital.true[,1] == x[1] & dat_state_capital.true[,2] == y) != 0)) {
      return(NULL)
    }
    return(y)
  }))
  return(data.frame(src=x[1], 
                    dst=sample(candidates, FALSE_PER_TRUE),
                    label=F))
}))

colnames(dat_state_capital.true) <- c("src","dst","label")
dat_state_capital <- rbind(dat_state_capital.true, dat_state_capital.false)
```

```{r}
tmp.paths <- read.csv("./Predicate_paths/capitals_3.csv")
tmp.paths$X <- NULL
tmp.paths
```

```{r}
res_capital_state <- list()
res_capital_state[["raw"]] <- tmp.paths
res_capital_state[["model"]] <- Logistic(label~.,res_capital_state[["raw"]])
res_capital_state[["eval"]] <- evaluate_Weka_classifier(res_capital_state[["model"]], numFolds = 10, complexity = T, class = T, seed = 233)
res_capital_state[["eval"]]
```

```{r}
# ---- Feature selection validation ----
weights_capital_state <- information.gain(label~., res_capital_state[["raw"]])
weights_capital_state <- weights_capital_state[order(weights_capital_state[,1], decreasing = T),,drop=F]

# ---- Top related relations ----
features_captial_state <- data.frame(importance=weights_capital_state$attr_importance, path=row.names(weights_capital_state))

features_captial_state <- features_captial_state[order(-features_captial_state$importance),]
#features_captial_state$path <- idpath2title(features_captial_state$path, mapfile)
head(weights_capital_state)
head(features_captial_state)
```

```{r}
# ---- AOROC of predicated sub paths ----
fm_val <- function(resdf) {
  return(as.numeric(str_split(str_split(resdf$eval$string,"\n")[[1]][24], " +")[[1]][9]))
}
full_predicated_path <- res_capital_state[["raw"]]
cl <- makeCluster(1) 
clusterExport(cl = cl, varlist=c("full_predicated_path", "weights_capital_state", "eval.df", "cutoff.k", "fm_val","str_split",
                               "as.numeric"), envir = environment())
res_AOROC <- rbind.fill(parLapply(cl, seq(1,ncol(full_predicated_path)-1,by = 5), function(x){
library(FSelector)
library(RWeka)
wekares<-eval.df(full_predicated_path[,c("label", cutoff.k(weights_capital_state, x))])
return(data.frame(AOROC=fm_val(wekares),nfeature=x))
}))
stopCluster(cl)
```

```{r}
install.packages("repr")
library(repr)
options(repr.plot.width=6, repr.plot.height=3)
ggplot(data=res_AOROC, aes(x=nfeature, y=AOROC, group=1)) +
  geom_line(color="red")+
  geom_point()
```


